### ISSUE TITLE
Finalize ML architecture implementation

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#354]
## Overview
We have work in a couple of places, so this issue should help to glue together what we are doing.

Going off of this [image](https://docs.google.com/drawings/d/1hVR1TosCTINKbo0nAad3-Ju3yYyyKEdRE1yjBU_1jPk/edit):

<img width="634" alt="Screen Shot 2021-12-13 at 12 33 14 PM" src="https://user-images.githubusercontent.com/51685858/145860517-4e122291-1fc0-461d-b4c0-60be2c2c938a.png">

# Todo

- [x] Extension #351, @danielgoldelman 
- [x] Offline Data Processing, [issue-17-other-repo](https://github.com/privacy-tech-lab/privacy-pioneer-data-and-scripts/issues/17), @notowen333 
- [x] Training (collab), [issue-18-other-repo](https://github.com/privacy-tech-lab/privacy-pioneer-data-and-scripts/issues/18), anyone
- [ ] Run-Time-Inference, this is the left side of the image #352 relates. This is lowest priority and can be configured once we get everything else straight.

**We are pursuing these issues more-or-less concurrently, but we should make sure to see tasks all the way through and move the overall project forward.**

**Comment by SebastianZimmeck** [comment]
cc'ing @harkous

**Comment by notowen333** [comment]
@danielgoldelman and I made this updated diagram today:

![MlPipeline drawio](https://user-images.githubusercontent.com/51685858/161116369-c27f48a3-ee7a-4ea8-924d-f1b0fc045048.png)

**Comment by SebastianZimmeck** [comment]
Nice! 

Depending on the absolute number of instances we train, validate, and test on, we may want to increase the test percentage as that is what our performance numbers for the paper will be based on. (Cross-validation may also be an option; three sets is good as is, just wanted to mention it.)

**Comment by danielgoldelman** [comment]
There is nothing concrete for us to do in the near future, but the ideas in this issue are still correct, as it shows our methodology moving forward. We will leave the issue open for reference and close at a later date when the ML model has been adequately implemented.

**Comment by SebastianZimmeck** [comment]
@danielgoldelman is on the lead on this issue and will have an initial discussion with @JustinCasler to reinforce our efforts a bit here.
